Ajuste correccion de pipeline de CD

diff --git a/.github/workflows/cd-pipeline.yml b/.github/workflows/cd-pipeline.yml
--- a/.github/workflows/cd-pipeline.yml
+++ b/.github/workflows/cd-pipeline.yml
@@ -39,7 +39,6 @@ jobs:
         run: |
           cd terraform
           TF_LOG=DEBUG terraform apply -auto-approve
-
   deploy_k8s:
     runs-on: ubuntu-latest
     needs: deploy_infra
@@ -59,9 +58,13 @@ jobs:
       - name: Configure Kubeconfig
         run: |
           mkdir -p ~/.kube
-          minikube update-context
-          minikube kubectl -- config view --minify > ~/.kube/config
+          minikube update-context || echo "Failed to update context"
+          minikube kubectl -- config view --raw > ~/.kube/config
           export KUBECONFIG=~/.kube/config
+          kubectl config use-context minikube || echo "Failed to set context"
+
+      - name: Verify Kubernetes Context
+        run: kubectl config get-contexts
 
       - name: Set up kubectl
         uses: azure/setup-kubectl@v1
@@ -73,7 +76,6 @@ jobs:
 
       - name: Check Kubernetes Pods
         run: kubectl get pods -A
-
   ansible:
     runs-on: ubuntu-latest
     needs: deploy_k8s
